### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by DazornSama** [DazornSama/fuwai#14]
### Summary

Each HTTP request to API should be authenticated.
Authentication is built on top of users registered in self-hosted instances of Fuwai.

### Dependencies

- #11 

### What should be done

- [ ] Provide an authentication endpoint which returns an `access_token`
- [ ] Provide an endpoint for refreshing tokens
- [ ] Add an authentication middleware to be executed on every HTTP request to API

### Expected result

Once an user registers itself, he should be able to authenticate and then make requests to API. Also, each application using API should be able to refresh tokens without asking user to authenticate again.
