### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by DazornSama** [DazornSama/fuwai#6]
### Summary

Logging is a nice-to-have feature once structured well. All the logs should be easily reachable and searchable.
[Grafana](https://grafana.com/) and [Grafana Loki](https://grafana.com/oss/loki/) could be a self-hostable solution to improve Fuwai's logging system.

### Dependencies

- #5 

### What should be done

- [ ] Add **Grafana** and **Grafana Loki** nodes to Docker compose file
- [ ] Ensure every log line produced by Fuwai arrives to **Grafana Loki** collector
- [ ] Provide a basic dashboard on **Grafana** for viewing logs

### Expected result

Logs should be easy to find and to inspect with meaningful information
