### ISSUE TITLE
README

### ISSUE THREAD

**Issue by DazornSama** [DazornSama/fuwai#9]
### Summary

A well formatted README file for a repository is a nice-to-have utility, because it explains what the repository is about and how work with it.

### What should be done

- [ ] Write an _introduction_ section
- [ ] Prepare a _getting started_ section
- [ ] Prepare a _development_ section
- [ ] Prepare a _deployment_ section
- [ ] Prepare a _contributing_ section
- [ ] Prepare a _community_ section

### Expected result

Fuwai's repository README file should be easy to read and fullfilled with all needed information
